name: hw2-sarcasm
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - tqdm
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - transformers==4.41.2
      - tokenizers==0.19.1